param(
  [string]$PythonVersion = "3.11.9",
  [string]$RuntimeDir = "src-tauri\bundled\faster-whisper",
  [switch]$Force
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
Set-Location $repoRoot

$runtimePath = Join-Path $repoRoot $RuntimeDir
$pythonExe = Join-Path $runtimePath "python.exe"
$sitePackages = Join-Path $runtimePath "Lib\site-packages"
$marker = Join-Path $runtimePath ".voice-mcp-host-faster-whisper-ready"

if ((Test-Path $marker) -and -not $Force) {
  Write-Host "Bundled faster-whisper runtime already exists: $runtimePath"
  exit 0
}

if ($Force -and (Test-Path $runtimePath)) {
  Remove-Item -LiteralPath $runtimePath -Recurse -Force
}

New-Item -ItemType Directory -Force -Path $runtimePath | Out-Null
New-Item -ItemType Directory -Force -Path $sitePackages | Out-Null

$pythonZipName = "python-$PythonVersion-embed-amd64.zip"
$pythonZipUrl = "https://www.python.org/ftp/python/$PythonVersion/$pythonZipName"
$pythonZipPath = Join-Path $env:TEMP $pythonZipName
$getPipPath = Join-Path $env:TEMP "voice-mcp-host-get-pip.py"

if (-not (Test-Path $pythonZipPath)) {
  Write-Host "Downloading portable Python $PythonVersion..."
  Invoke-WebRequest -Uri $pythonZipUrl -OutFile $pythonZipPath
}

Write-Host "Extracting portable Python..."
Expand-Archive -LiteralPath $pythonZipPath -DestinationPath $runtimePath -Force

$pthFile = Get-ChildItem -LiteralPath $runtimePath -Filter "python*._pth" | Select-Object -First 1
if (-not $pthFile) {
  throw "Python embed _pth file was not found in $runtimePath"
}

$pthLines = Get-Content -LiteralPath $pthFile.FullName
$patched = @()
foreach ($line in $pthLines) {
  if ($line.Trim() -eq "#import site") {
    $patched += "import site"
  } else {
    $patched += $line
  }
}
if ($patched -notcontains "Lib\site-packages") {
  $patched += "Lib\site-packages"
}
Set-Content -LiteralPath $pthFile.FullName -Value $patched -Encoding ASCII

if (-not (Test-Path $getPipPath)) {
  Write-Host "Downloading pip bootstrap..."
  Invoke-WebRequest -Uri "https://bootstrap.pypa.io/get-pip.py" -OutFile $getPipPath
}

Write-Host "Installing pip into bundled Python..."
& $pythonExe $getPipPath --no-warn-script-location

Write-Host "Installing faster-whisper runtime packages..."
& $pythonExe -m pip install --upgrade --no-warn-script-location `
  --target $sitePackages `
  faster-whisper

@"
voice-mcp-host bundled faster-whisper runtime

Python: $PythonVersion
Created: $(Get-Date -Format o)

This directory is generated by scripts/prepare-faster-whisper-windows.ps1
and is bundled into the Windows installer.
"@ | Set-Content -LiteralPath (Join-Path $runtimePath "README.txt") -Encoding UTF8

"" | Set-Content -LiteralPath $marker -Encoding ASCII

Write-Host "Verifying faster-whisper preflight..."
& $pythonExe "src-tauri\sidecars\voice_mcp_asr_sidecar.py" --preflight --json

Write-Host "Bundled faster-whisper runtime is ready: $runtimePath"
